### ISSUE TITLE
PaginationStore

### ISSUE THREAD

**Issue by LucaFrancis** [BiggA94/resub-entity#4]
It would be nice to have a PaginationStore, which can dynamically load chunks of data. 
Support for getting entities based on an amount and a page would help when working with older pagination systems.

**Comment by BiggA94** [comment]
@LucaFrancis any comments?

**Comment by LucaFrancis** [comment]
Very nice, I enjoy the option to use both pagenumber/pagesize and lastEntity/pagesize
